file_format: "1"
id: beedev
name: beedev
type: shield
url: https://github.com/Count-I/zmk-config-beedev
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - beedev_left
  - beedev_right